main: me.Magnusri.DragonBusiness2.DragonBusiness2
name: DragonBusiness2
version: 1
author: Magnusri
description: Business Plugin!
depend: [Vault]

commands:
  company:
    aliases: [c, co]
    description: 
  paybonus: