main: me.Magnusri.DragonBusiness2.DragonBusiness2
name: DragonBusiness2
version: 1
author: Magnusri
description: Creates Businesses
depend: [Vault]

commands:
  company:
    aliases: [c, co]
    description:
